version: '3.8'

services:
  flavumhive:
    build: .
    container_name: flavumhive
    restart: always
    env_file:
      - .env
    volumes:
      - ./reddit_bot.db:/app/reddit_bot.db
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
        max-file: "10" 